version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=myUser
      - DATABASE_PASSWORD=myPass
      - DATABASE_NAME=voucher_promotion_db_dev
      - PORT=3001
    ports:
      - '3001:3001' # Map port 3001 on the host to port 3001 in the container
    depends_on:
      - postgres
    command: ["npm", "run", "start:prod"] # Ensure production build is running

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPass
      POSTGRES_DB: voucher_promotion_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Expose PostgreSQL on the host

volumes:
  postgres_data:
    driver: local
